# Generated by Django 2.1 on 2019-04-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertingtodatabasemeasurement',
            name='number_of_rendered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renderingtemplatemeasurement',
            name='number_of_rendered',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
