# Generated by Django 2.1 on 2019-04-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190425_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertingtodatabasemeasurement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='renderingtemplatemeasurement',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
