# Generated by Django 2.1 on 2019-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190426_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalApiCallMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('execution_time', models.FloatField()),
                ('framework', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'external_api_call_measurement',
            },
        ),
    ]
