# Generated by Django 2.1 on 2019-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_externalapicallmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONSerializationMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('execution_time', models.FloatField()),
                ('framework', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'json_serialization_measurement',
            },
        ),
    ]
