version: '3'

services:
  mysql_compare:
    container_name: "mysql"
    image: mysql:latest
    ports:
      - "3312:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "compare_py_web_frameworks"
    command: --default-authentication-plugin=mysql_native_password
  web:
    container_name: "compare_py_web_frameworks"
    build: .
    command: bash -c "./wait-for-it.sh -t 0 mysql_compare:3306 -- python manage.py migrate && python manage.py loaddata db_fixtures.json && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - mysql
    depends_on:
      - grafana
    links:
      - mysql_compare
    ports:
      - "8002:8002"
  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    ports:
      - "3000:3000"
    links:
      - mysql_compare
    volumes: 
      - ./grafana:/var/lib/grafana
